name: ci
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check formatting
        run: make format-check

      - name: Build (strict)
        run: make fclean all BUILD=dev CFLAGS+="-Wunused-parameter -Wunused-function"

      # - name: Smoke test
      #   run: ./ft_ping --hel
